version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: studypartner
      POSTGRES_USER: studypartner
      POSTGRES_PASSWORD: studypartner123
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studypartner -d studypartner"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Ollama for local AI models
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    profiles:
      - ai

volumes:
  postgres_data:
  ollama_data:
